[project]
name = "pslogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "structlog>=24.4.0",
    "logfire>=1.3.0",
]
